version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - ganache
    command: ["./wait-for-it.sh", "ganache:8545", "--", "../bin/app"]

  ganache:
    image: trufflesuite/ganache-cli:v6.12.2
    ports:
      - "8545:8545"
